import os

def populate():

    add_post(title="We are all Nachos",
    story="I love cheese, especially cauliflower cheese airedale. Caerphilly mascarpone red leicester cream cheese croque monsieur cheesecake dolcelatte squirty cheese. Babybel bocconcini edam parmesan cut the cheese say cheese airedale say cheese. Fondue stilton cream cheese rubber cheese macaroni cheese cheeseburger taleggio cheese triangles. The big cheese.rieue castello cow. St. agur blue cheese stilton hard cheese smelly cheese cheese slices cheese and biscuits stinking bishop cheese strings. Camembert de normandie cut the cheese bavarian bergkase halloumi goat cheese strings cut the cheese stinking bishop. Melted cheese lancashire caerphilly swiss cut the cheese cheese and biscuits smelly cheese airedale. Red leicester cheeseburger fromage.Cauliflower cheese gouda queso. Jarlsberg babybel boursin ricotta brie cheese and wine cheese and biscuits goat. The big cheese squirty cheese the big cheese brie port-salut pecorino airedale rubber cheese. Cheeseburger dolcelatte fromage frais brie parmesan croque monsieur.Cream cheese cheese and wine macaroni cheese. Fromage frais paneer manchego stinking bishop cheddar cheeseburger caerphilly dolcelatte. Manchego bavarian bergkase goat cheese on toast halloumi the big cheese rubber cheese dolcelatte. Goat taleggio cow.")

    add_post(title="Marzipane is Poop",
    story="I love cheese, especially cauliflower cheese airedale. Caerphilly mascarpone red leicester cream cheese croque monsieur cheesecake dolcelatte squirty cheese. Babybel bocconcini edam parmesan cut the cheese say cheese airedale say cheese. Fondue stilton cream cheese rubber cheese macaroni cheese cheeseburger taleggio cheese triangles. The big cheese.rieue castello cow. St. agur blue cheese stilton hard cheese smelly cheese cheese slices cheese and biscuits stinking bishop cheese strings. Camembert de normandie cut the cheese bavarian bergkase halloumi goat cheese strings cut the cheese stinking bishop. Melted cheese lancashire caerphilly swiss cut the cheese cheese and biscuits smelly cheese airedale. Red leicester cheeseburger fromage.Cauliflower cheese gouda queso. Jarlsberg babybel boursin ricotta brie cheese and wine cheese and biscuits goat. The big cheese squirty cheese the big cheese brie port-salut pecorino airedale rubber cheese. Cheeseburger dolcelatte fromage frais brie parmesan croque monsieur.Cream cheese cheese and wine macaroni cheese. Fromage frais paneer manchego stinking bishop cheddar cheeseburger caerphilly dolcelatte. Manchego bavarian bergkase goat cheese on toast halloumi the big cheese rubber cheese dolcelatte. Goat taleggio cow.")

    add_post(title="Dying on the Moon",
    story="I love cheese, especially cauliflower cheese airedale. Caerphilly mascarpone red leicester cream cheese croque monsieur cheesecake dolcelatte squirty cheese. Babybel bocconcini edam parmesan cut the cheese say cheese airedale say cheese. Fondue stilton cream cheese rubber cheese macaroni cheese cheeseburger taleggio cheese triangles. The big cheese.rieue castello cow. St. agur blue cheese stilton hard cheese smelly cheese cheese slices cheese and biscuits stinking bishop cheese strings. Camembert de normandie cut the cheese bavarian bergkase halloumi goat cheese strings cut the cheese stinking bishop. Melted cheese lancashire caerphilly swiss cut the cheese cheese and biscuits smelly cheese airedale. Red leicester cheeseburger fromage.Cauliflower cheese gouda queso. Jarlsberg babybel boursin ricotta brie cheese and wine cheese and biscuits goat. The big cheese squirty cheese the big cheese brie port-salut pecorino airedale rubber cheese. Cheeseburger dolcelatte fromage frais brie parmesan croque monsieur.Cream cheese cheese and wine macaroni cheese. Fromage frais paneer manchego stinking bishop cheddar cheeseburger caerphilly dolcelatte. Manchego bavarian bergkase goat cheese on toast halloumi the big cheese rubber cheese dolcelatte. Goat taleggio cow.")

    add_post(title="A story of love",
    story="I love cheese, especially cauliflower cheese airedale. Caerphilly mascarpone red leicester cream cheese croque monsieur cheesecake dolcelatte squirty cheese. Babybel bocconcini edam parmesan cut the cheese say cheese airedale say cheese. Fondue stilton cream cheese rubber cheese macaroni cheese cheeseburger taleggio cheese triangles. The big cheese.rieue castello cow. St. agur blue cheese stilton hard cheese smelly cheese cheese slices cheese and biscuits stinking bishop cheese strings. Camembert de normandie cut the cheese bavarian bergkase halloumi goat cheese strings cut the cheese stinking bishop. Melted cheese lancashire caerphilly swiss cut the cheese cheese and biscuits smelly cheese airedale. Red leicester cheeseburger fromage.Cauliflower cheese gouda queso. Jarlsberg babybel boursin ricotta brie cheese and wine cheese and biscuits goat. The big cheese squirty cheese the big cheese brie port-salut pecorino airedale rubber cheese. Cheeseburger dolcelatte fromage frais brie parmesan croque monsieur.Cream cheese cheese and wine macaroni cheese. Fromage frais paneer manchego stinking bishop cheddar cheeseburger caerphilly dolcelatte. Manchego bavarian bergkase goat cheese on toast halloumi the big cheese rubber cheese dolcelatte. Goat taleggio cow.")

    add_post(title="A story of sex",
    story="I love cheese, especially cauliflower cheese airedale. Caerphilly mascarpone red leicester cream cheese croque monsieur cheesecake dolcelatte squirty cheese. Babybel bocconcini edam parmesan cut the cheese say cheese airedale say cheese. Fondue stilton cream cheese rubber cheese macaroni cheese cheeseburger taleggio cheese triangles. The big cheese.rieue castello cow. St. agur blue cheese stilton hard cheese smelly cheese cheese slices cheese and biscuits stinking bishop cheese strings. Camembert de normandie cut the cheese bavarian bergkase halloumi goat cheese strings cut the cheese stinking bishop. Melted cheese lancashire caerphilly swiss cut the cheese cheese and biscuits smelly cheese airedale. Red leicester cheeseburger fromage.Cauliflower cheese gouda queso. Jarlsberg babybel boursin ricotta brie cheese and wine cheese and biscuits goat. The big cheese squirty cheese the big cheese brie port-salut pecorino airedale rubber cheese. Cheeseburger dolcelatte fromage frais brie parmesan croque monsieur.Cream cheese cheese and wine macaroni cheese. Fromage frais paneer manchego stinking bishop cheddar cheeseburger caerphilly dolcelatte. Manchego bavarian bergkase goat cheese on toast halloumi the big cheese rubber cheese dolcelatte. Goat taleggio cow.")

    add_post(title="Lovely sex story",
    story="I love cheese, especially cauliflower cheese airedale. Caerphilly mascarpone red leicester cream cheese croque monsieur cheesecake dolcelatte squirty cheese. Babybel bocconcini edam parmesan cut the cheese say cheese airedale say cheese. Fondue stilton cream cheese rubber cheese macaroni cheese cheeseburger taleggio cheese triangles. The big cheese.rieue castello cow. St. agur blue cheese stilton hard cheese smelly cheese cheese slices cheese and biscuits stinking bishop cheese strings. Camembert de normandie cut the cheese bavarian bergkase halloumi goat cheese strings cut the cheese stinking bishop. Melted cheese lancashire caerphilly swiss cut the cheese cheese and biscuits smelly cheese airedale. Red leicester cheeseburger fromage.Cauliflower cheese gouda queso. Jarlsberg babybel boursin ricotta brie cheese and wine cheese and biscuits goat. The big cheese squirty cheese the big cheese brie port-salut pecorino airedale rubber cheese. Cheeseburger dolcelatte fromage frais brie parmesan croque monsieur.Cream cheese cheese and wine macaroni cheese. Fromage frais paneer manchego stinking bishop cheddar cheeseburger caerphilly dolcelatte. Manchego bavarian bergkase goat cheese on toast halloumi the big cheese rubber cheese dolcelatte. Goat taleggio cow.")

    add_post(title="Oh, please, read me, please",
    story="I love cheese, especially cauliflower cheese airedale. Caerphilly mascarpone red leicester cream cheese croque monsieur cheesecake dolcelatte squirty cheese. Babybel bocconcini edam parmesan cut the cheese say cheese airedale say cheese. Fondue stilton cream cheese rubber cheese macaroni cheese cheeseburger taleggio cheese triangles. The big cheese.rieue castello cow. St. agur blue cheese stilton hard cheese smelly cheese cheese slices cheese and biscuits stinking bishop cheese strings. Camembert de normandie cut the cheese bavarian bergkase halloumi goat cheese strings cut the cheese stinking bishop. Melted cheese lancashire caerphilly swiss cut the cheese cheese and biscuits smelly cheese airedale. Red leicester cheeseburger fromage.Cauliflower cheese gouda queso. Jarlsberg babybel boursin ricotta brie cheese and wine cheese and biscuits goat. The big cheese squirty cheese the big cheese brie port-salut pecorino airedale rubber cheese. Cheeseburger dolcelatte fromage frais brie parmesan croque monsieur.Cream cheese cheese and wine macaroni cheese. Fromage frais paneer manchego stinking bishop cheddar cheeseburger caerphilly dolcelatte. Manchego bavarian bergkase goat cheese on toast halloumi the big cheese rubber cheese dolcelatte. Goat taleggio cow.")


def add_post(title, story):
    p = Post.objects.get_or_create(title=title, story=story)[0]
    return p

# Start execution here!
if __name__ == '__main__':
    print "Starting Blog population script..."
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'lynn_isaac.settings')
    from blog.models import Post
    populate()